import { TMovie, TUser } from "../types";

export const users: (TUser & { password: string })[] = [
  {
    id: "1",
    email: "test@test.com",
    name: "Alexandro Tapia",
    picture: "/users/test@test.com/picture.png",
    password: "123456",
    purchasedMovieIds: ["1", "4", "3", "10", "13", "16", "20", "5", "2", "7"],
  },
];
export const movies: TMovie[] = [
  {
    id: "1",
    title: "The Shawshank Redemption",
    banner: "/movies/The Shawshank Redemption/banner.jpg",
    cover: "/movies/The Shawshank Redemption/cover.jpg",
    ratings: 9.3,
    durationInSeconds: 8520,
    director: "Frank Darabont",
    year: 1994,
    genres: ["Drama"],
    description:
      "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    priceInCents: 1299,
  },
  {
    id: "2",
    title: "The Godfather",
    banner: "/movies/The Godfather/banner.jpg",
    cover: "/movies/The Godfather/cover.jpg",
    ratings: 9.2,
    durationInSeconds: 10500,
    director: "Francis Ford Coppola",
    year: 1972,
    genres: ["Crime", "Drama"],
    description:
      "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    priceInCents: 1399,
  },
  {
    id: "3",
    title: "The Dark Knight",
    banner: "/movies/The Dark Knight/banner.jpg",
    cover: "/movies/The Dark Knight/cover.jpg",
    ratings: 9.0,
    durationInSeconds: 9120,
    director: "Christopher Nolan",
    year: 2008,
    genres: ["Action", "Crime", "Drama"],
    description:
      "When the menace known as the Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham.",
    priceInCents: 1199,
  },
  {
    id: "4",
    title: "Pulp Fiction",
    banner: "/movies/Pulp Fiction/banner.jpg",
    cover: "/movies/Pulp Fiction/cover.jpg",
    ratings: 8.9,
    durationInSeconds: 9480,
    director: "Quentin Tarantino",
    year: 1994,
    genres: ["Crime", "Drama"],
    description:
      "The lives of two mob hitmen, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    priceInCents: 1299,
  },
  {
    id: "5",
    title: "Forrest Gump",
    banner: "/movies/Forrest Gump/banner.jpg",
    cover: "/movies/Forrest Gump/cover.jpg",
    ratings: 8.8,
    durationInSeconds: 8520,
    director: "Robert Zemeckis",
    year: 1994,
    genres: ["Drama", "Romance"],
    description:
      "The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate, and other history unfold through the perspective of an Alabama man with an IQ of 75.",
    priceInCents: 1199,
  },
  {
    id: "6",
    title: "Inception",
    banner: "/movies/Inception/banner.jpg",
    cover: "/movies/Inception/cover.jpg",
    ratings: 8.8,
    durationInSeconds: 8880,
    director: "Christopher Nolan",
    year: 2010,
    genres: ["Action", "Adventure", "Sci-Fi"],
    description:
      "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.",
    priceInCents: 1399,
  },
  {
    id: "7",
    title: "Fight Club",
    banner: "/movies/Fight Club/banner.jpg",
    cover: "/movies/Fight Club/cover.jpg",
    ratings: 8.8,
    durationInSeconds: 8340,
    director: "David Fincher",
    year: 1999,
    genres: ["Drama"],
    description:
      "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
    priceInCents: 1299,
  },
  {
    id: "8",
    title: "The Matrix",
    banner: "/movies/The Matrix/banner.jpg",
    cover: "/movies/The Matrix/cover.jpg",
    ratings: 8.7,
    durationInSeconds: 8160,
    director: "Lana Wachowski, Lilly Wachowski",
    year: 1999,
    genres: ["Action", "Sci-Fi"],
    description:
      "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
    priceInCents: 1199,
  },
  {
    id: "9",
    title: "Goodfellas",
    banner: "/movies/Goodfellas/banner.jpg",
    cover: "/movies/Goodfellas/cover.jpg",
    ratings: 8.7,
    durationInSeconds: 8880,
    director: "Martin Scorsese",
    year: 1990,
    genres: ["Biography", "Crime", "Drama"],
    description:
      "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito.",
    priceInCents: 1399,
  },
  {
    id: "10",
    title: "The Lord of the Rings: The Return of the King",
    banner: "/movies/The Lord of the Rings: The Return of the King/banner.jpg",
    cover: "/movies/The Lord of the Rings: The Return of the King/cover.jpg",
    ratings: 8.9,
    durationInSeconds: 12600,
    director: "Peter Jackson",
    year: 2003,
    genres: ["Adventure", "Drama", "Fantasy"],
    description:
      "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
    priceInCents: 1499,
  },
  {
    id: "11",
    title: "The Silence of the Lambs",
    banner: "/movies/The Silence of the Lambs/banner.jpg",
    cover: "/movies/The Silence of the Lambs/cover.jpg",
    ratings: 8.6,
    durationInSeconds: 7080,
    director: "Jonathan Demme",
    year: 1991,
    genres: ["Crime", "Drama", "Thriller"],
    description:
      "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to catch another serial killer, a madman who skins his victims.",
    priceInCents: 1299,
  },
  {
    id: "12",
    title: "Schindler's List",
    banner: "/movies/Schindler's List/banner.jpg",
    cover: "/movies/Schindler's List/cover.jpg",
    ratings: 8.9,
    durationInSeconds: 11700,
    director: "Steven Spielberg",
    year: 1993,
    genres: ["Biography", "Drama", "History"],
    description:
      "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
    priceInCents: 1499,
  },
  {
    id: "13",
    title: "The Green Mile",
    banner: "/movies/The Green Mile/banner.jpg",
    cover: "/movies/The Green Mile/cover.jpg",
    ratings: 8.6,
    durationInSeconds: 11400,
    director: "Frank Darabont",
    year: 1999,
    genres: ["Crime", "Drama", "Fantasy"],
    description:
      "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.",
    priceInCents: 1399,
  },
  {
    id: "14",
    title: "Interstellar",
    banner: "/movies/Interstellar/banner.jpg",
    cover: "/movies/Interstellar/cover.jpg",
    ratings: 8.6,
    durationInSeconds: 10140,
    director: "Christopher Nolan",
    year: 2014,
    genres: ["Adventure", "Drama", "Sci-Fi"],
    description:
      "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    priceInCents: 1499,
  },
  {
    id: "15",
    title: "The Usual Suspects",
    banner: "/movies/The Usual Suspects/banner.jpg",
    cover: "/movies/The Usual Suspects/cover.jpg",
    ratings: 8.5,
    durationInSeconds: 6360,
    director: "Bryan Singer",
    year: 1995,
    genres: ["Crime", "Drama", "Mystery"],
    description:
      "A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which began when five criminals met at a seemingly random police lineup.",
    priceInCents: 1299,
  },
  {
    id: "16",
    title: "The Lion King",
    banner: "/movies/The Lion King/banner.jpg",
    cover: "/movies/The Lion King/cover.jpg",
    ratings: 8.5,
    durationInSeconds: 5280,
    director: "Roger Allers, Rob Minkoff",
    year: 1994,
    genres: ["Animation", "Adventure", "Drama"],
    description:
      "Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.",
    priceInCents: 1199,
  },
  {
    id: "17",
    title: "Gladiator",
    banner: "/movies/Gladiator/banner.jpg",
    cover: "/movies/Gladiator/cover.jpg",
    ratings: 8.5,
    durationInSeconds: 9300,
    director: "Ridley Scott",
    year: 2000,
    genres: ["Action", "Adventure", "Drama"],
    description:
      "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
    priceInCents: 1299,
  },
  {
    id: "18",
    title: "The Prestige",
    banner: "/movies/The Prestige/banner.jpg",
    cover: "/movies/The Prestige/cover.jpg",
    ratings: 8.5,
    durationInSeconds: 7800,
    director: "Christopher Nolan",
    year: 2006,
    genres: ["Drama", "Mystery", "Sci-Fi"],
    description:
      "After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.",
    priceInCents: 1299,
  },
  {
    id: "19",
    title: "The Departed",
    banner: "/movies/The Departed/banner.jpg",
    cover: "/movies/The Departed/cover.jpg",
    ratings: 8.5,
    durationInSeconds: 9120,
    director: "Martin Scorsese",
    year: 2006,
    genres: ["Crime", "Drama", "Thriller"],
    description:
      "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.",
    priceInCents: 1399,
  },
  {
    id: "20",
    title: "Whiplash",
    banner: "/movies/Whiplash/banner.jpg",
    cover: "/movies/Whiplash/cover.jpg",
    ratings: 8.5,
    durationInSeconds: 6420,
    director: "Damien Chazelle",
    year: 2014,
    genres: ["Drama", "Music"],
    description:
      "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.",
    priceInCents: 1299,
  },
];
