import { TMovie, TUser } from "../types";

export const users: (TUser & { password: string })[] = [
  {
    id: "1",
    email: "alexandrotapiaflores@gmail.com",
    name: "Alexandro Tapia",
    password: "123456",
  },
  {
    id: "2",
    email: "alexandro@zpaceway.com",
    name: "Andrés Tapia",
    password: "AABBCC",
  },
];

export const movies: TMovie[] = [
  {
    id: "1",
    name: "The Shawshank Redemption",
    banner: "/movies/The Shawshank Redemption/banner.jpg",
    cover: "/movies/The Shawshank Redemption/cover.jpg",
    ratings: 9.3,
    durationInSeconds: 8520,
    director: "Frank Darabont",
    year: 1994,
    genres: ["Drama"],
    description:
      "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
  },
  {
    id: "2",
    name: "The Godfather",
    banner: "/movies/The Godfather/banner.jpg",
    cover: "/movies/The Godfather/cover.jpg",
    ratings: 9.2,
    durationInSeconds: 10500,
    director: "Francis Ford Coppola",
    year: 1972,
    genres: ["Crime", "Drama"],
    description:
      "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
  },
  {
    id: "3",
    name: "The Dark Knight",
    banner: "/movies/The Dark Knight/banner.jpg",
    cover: "/movies/The Dark Knight/cover.jpg",
    ratings: 9.0,
    durationInSeconds: 9120,
    director: "Christopher Nolan",
    year: 2008,
    genres: ["Action", "Crime", "Drama"],
    description:
      "When the menace known as the Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham.",
  },
  {
    id: "4",
    name: "Pulp Fiction",
    banner: "/movies/Pulp Fiction/banner.jpg",
    cover: "/movies/Pulp Fiction/cover.jpg",
    ratings: 8.9,
    durationInSeconds: 9480,
    director: "Quentin Tarantino",
    year: 1994,
    genres: ["Crime", "Drama"],
    description:
      "The lives of two mob hitmen, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
  },
  {
    id: "5",
    name: "Forrest Gump",
    banner: "/movies/Forrest Gump/banner.jpg",
    cover: "/movies/Forrest Gump/cover.jpg",
    ratings: 8.8,
    durationInSeconds: 8520,
    director: "Robert Zemeckis",
    year: 1994,
    genres: ["Drama", "Romance"],
    description:
      "The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate, and other history unfold through the perspective of an Alabama man with an IQ of 75.",
  },
  {
    id: "6",
    name: "Inception",
    banner: "/movies/Inception/banner.jpg",
    cover: "/movies/Inception/cover.jpg",
    ratings: 8.8,
    durationInSeconds: 8880,
    director: "Christopher Nolan",
    year: 2010,
    genres: ["Action", "Adventure", "Sci-Fi"],
    description:
      "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.",
  },
  {
    id: "7",
    name: "Fight Club",
    banner: "/movies/Fight Club/banner.jpg",
    cover: "/movies/Fight Club/cover.jpg",
    ratings: 8.8,
    durationInSeconds: 8340,
    director: "David Fincher",
    year: 1999,
    genres: ["Drama"],
    description:
      "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
  },
  {
    id: "8",
    name: "The Matrix",
    banner: "/movies/The Matrix/banner.jpg",
    cover: "/movies/The Matrix/cover.jpg",
    ratings: 8.7,
    durationInSeconds: 8160,
    director: "Lana Wachowski, Lilly Wachowski",
    year: 1999,
    genres: ["Action", "Sci-Fi"],
    description:
      "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
  },
  {
    id: "9",
    name: "Goodfellas",
    banner: "/movies/Goodfellas/banner.jpg",
    cover: "/movies/Goodfellas/cover.jpg",
    ratings: 8.7,
    durationInSeconds: 8880,
    director: "Martin Scorsese",
    year: 1990,
    genres: ["Biography", "Crime", "Drama"],
    description:
      "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito.",
  },
  {
    id: "10",
    name: "The Lord of the Rings: The Return of the King",
    banner: "/movies/The Lord of the Rings: The Return of the King/banner.jpg",
    cover: "/movies/The Lord of the Rings: The Return of the King/cover.jpg",
    ratings: 8.9,
    durationInSeconds: 12600,
    director: "Peter Jackson",
    year: 2003,
    genres: ["Adventure", "Drama", "Fantasy"],
    description:
      "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
  },
  {
    id: "11",
    name: "The Silence of the Lambs",
    banner: "/movies/The Silence of the Lambs/banner.jpg",
    cover: "/movies/The Silence of the Lambs/cover.jpg",
    ratings: 8.6,
    durationInSeconds: 7080,
    director: "Jonathan Demme",
    year: 1991,
    genres: ["Crime", "Drama", "Thriller"],
    description:
      "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to catch another serial killer, a madman who skins his victims.",
  },
  {
    id: "12",
    name: "Schindler's List",
    banner: "/movies/Schindler's List/banner.jpg",
    cover: "/movies/Schindler's List/cover.jpg",
    ratings: 8.9,
    durationInSeconds: 11700,
    director: "Steven Spielberg",
    year: 1993,
    genres: ["Biography", "Drama", "History"],
    description:
      "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
  },
  {
    id: "13",
    name: "The Green Mile",
    banner: "/movies/The Green Mile/banner.jpg",
    cover: "/movies/The Green Mile/cover.jpg",
    ratings: 8.6,
    durationInSeconds: 11400,
    director: "Frank Darabont",
    year: 1999,
    genres: ["Crime", "Drama", "Fantasy"],
    description:
      "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.",
  },
  {
    id: "14",
    name: "Interstellar",
    banner: "/movies/Interstellar/banner.jpg",
    cover: "/movies/Interstellar/cover.jpg",
    ratings: 8.6,
    durationInSeconds: 10140,
    director: "Christopher Nolan",
    year: 2014,
    genres: ["Adventure", "Drama", "Sci-Fi"],
    description:
      "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
  },
  {
    id: "15",
    name: "The Usual Suspects",
    banner: "/movies/The Usual Suspects/banner.jpg",
    cover: "/movies/The Usual Suspects/cover.jpg",
    ratings: 8.5,
    durationInSeconds: 6360,
    director: "Bryan Singer",
    year: 1995,
    genres: ["Crime", "Drama", "Mystery"],
    description:
      "A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which began when five criminals met at a seemingly random police lineup.",
  },
  {
    id: "16",
    name: "The Lion King",
    banner: "/movies/The Lion King/banner.jpg",
    cover: "/movies/The Lion King/cover.jpg",
    ratings: 8.5,
    durationInSeconds: 5280,
    director: "Roger Allers, Rob Minkoff",
    year: 1994,
    genres: ["Animation", "Adventure", "Drama"],
    description:
      "Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.",
  },
  {
    id: "17",
    name: "Gladiator",
    banner: "/movies/Gladiator/banner.jpg",
    cover: "/movies/Gladiator/cover.jpg",
    ratings: 8.5,
    durationInSeconds: 9300,
    director: "Ridley Scott",
    year: 2000,
    genres: ["Action", "Adventure", "Drama"],
    description:
      "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
  },
  {
    id: "18",
    name: "The Prestige",
    banner: "/movies/The Prestige/banner.jpg",
    cover: "/movies/The Prestige/cover.jpg",
    ratings: 8.5,
    durationInSeconds: 7800,
    director: "Christopher Nolan",
    year: 2006,
    genres: ["Drama", "Mystery", "Sci-Fi"],
    description:
      "After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.",
  },
  {
    id: "19",
    name: "The Departed",
    banner: "/movies/The Departed/banner.jpg",
    cover: "/movies/The Departed/cover.jpg",
    ratings: 8.5,
    durationInSeconds: 9120,
    director: "Martin Scorsese",
    year: 2006,
    genres: ["Crime", "Drama", "Thriller"],
    description:
      "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.",
  },
  {
    id: "20",
    name: "Whiplash",
    banner: "/movies/Whiplash/banner.jpg",
    cover: "/movies/Whiplash/cover.jpg",
    ratings: 8.5,
    durationInSeconds: 6420,
    director: "Damien Chazelle",
    year: 2014,
    genres: ["Drama", "Music"],
    description:
      "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.",
  },
  // {
  //   id: "21",
  //   name: "Django Unchained",
  //   banner: "/movies/Django Unchained/banner.jpg",
  //   cover: "/movies/Django Unchained/cover.jpg",
  //   ratings: 8.4,
  //   durationInSeconds: 10800,
  //   director: "Quentin Tarantino",
  //   year: 2012,
  //   genres: ["Drama", "Western"],
  //   description:
  //     "With the help of a German bounty-hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.",
  // },
  // {
  //   id: "22",
  //   name: "Braveheart",
  //   banner: "/movies/Braveheart/banner.jpg",
  //   cover: "/movies/Braveheart/cover.jpg",
  //   ratings: 8.4,
  //   durationInSeconds: 10800,
  //   director: "Mel Gibson",
  //   year: 1995,
  //   genres: ["Biography", "Drama", "History"],
  //   description:
  //     "Scottish warrior William Wallace leads his countrymen in a rebellion to free his homeland from the tyranny of King Edward I of England.",
  // },
  // {
  //   id: "23",
  //   name: "The Wolf of Wall Street",
  //   banner: "/movies/The Wolf of Wall Street/banner.jpg",
  //   cover: "/movies/The Wolf of Wall Street/cover.jpg",
  //   ratings: 8.2,
  //   durationInSeconds: 10800,
  //   director: "Martin Scorsese",
  //   year: 2013,
  //   genres: ["Biography", "Comedy", "Crime"],
  //   description:
  //     "Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption, and the federal government.",
  // },
  // {
  //   id: "24",
  //   name: "The Pianist",
  //   banner: "/movies/The Pianist/banner.jpg",
  //   cover: "/movies/The Pianist/cover.jpg",
  //   ratings: 8.5,
  //   durationInSeconds: 9000,
  //   director: "Roman Polanski",
  //   year: 2002,
  //   genres: ["Biography", "Drama", "Music"],
  //   description:
  //     "A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II.",
  // },
  // {
  //   id: "25",
  //   name: "Parasite",
  //   banner: "/movies/Parasite/banner.jpg",
  //   cover: "/movies/Parasite/cover.jpg",
  //   ratings: 8.6,
  //   durationInSeconds: 7920,
  //   director: "Bong Joon Ho",
  //   year: 2019,
  //   genres: ["Comedy", "Drama", "Thriller"],
  //   description:
  //     "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
  // },
  // {
  //   id: "26",
  //   name: "Avengers: Endgame",
  //   banner: "/movies/Avengers Endgame/banner.jpg",
  //   cover: "/movies/Avengers Endgame/cover.jpg",
  //   ratings: 8.4,
  //   durationInSeconds: 10800,
  //   director: "Anthony Russo, Joe Russo",
  //   year: 2019,
  //   genres: ["Action", "Adventure", "Drama"],
  //   description:
  //     "After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
  // },
  // {
  //   id: "27",
  //   name: "Saving Private Ryan",
  //   banner: "/movies/Saving Private Ryan/banner.jpg",
  //   cover: "/movies/Saving Private Ryan/cover.jpg",
  //   ratings: 8.6,
  //   durationInSeconds: 10200,
  //   director: "Steven Spielberg",
  //   year: 1998,
  //   genres: ["Drama", "War"],
  //   description:
  //     "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.",
  // },
  // {
  //   id: "28",
  //   name: "City of God",
  //   banner: "/movies/City of God/banner.jpg",
  //   cover: "/movies/City of God/cover.jpg",
  //   ratings: 8.6,
  //   durationInSeconds: 7860,
  //   director: "Fernando Meirelles, Kátia Lund",
  //   year: 2002,
  //   genres: ["Crime", "Drama"],
  //   description:
  //     "In the slums of Rio, two kids' paths diverge as one struggles to become a photographer and the other a kingpin.",
  // },
  // {
  //   id: "29",
  //   name: "Back to the Future",
  //   banner: "/movies/Back to the Future/banner.jpg",
  //   cover: "/movies/Back to the Future/cover.jpg",
  //   ratings: 8.5,
  //   durationInSeconds: 6960,
  //   director: "Robert Zemeckis",
  //   year: 1985,
  //   genres: ["Adventure", "Comedy", "Sci-Fi"],
  //   description:
  //     "Marty McFly, a 17-year-old high school student, is accidentally sent thirty years into the past in a time-traveling DeLorean invented by his close friend, eccentric scientist Doc Brown.",
  // },
  // {
  //   id: "30",
  //   name: "American Beauty",
  //   banner: "/movies/American Beauty/banner.jpg",
  //   cover: "/movies/American Beauty/cover.jpg",
  //   ratings: 8.3,
  //   durationInSeconds: 7320,
  //   director: "Sam Mendes",
  //   year: 1999,
  //   genres: ["Drama"],
  //   description:
  //     "A sexually frustrated suburban father has a mid-life crisis after becoming infatuated with his daughter's best friend.",
  // },
];
